version: '2'
services:
  # container for API
  api:
    image: kun391/phpup:1.0
    ports:
      - 9000:80
    depends_on:
      - db
    volumes:
      - .:/var/www/app
      - ./queue.conf:/etc/supervisor/conf.d/queue.conf
    environment:
      - PHP_MEM_LIMIT=1024M
  db:
    image: mysql:5.7
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9029:80
    depends_on:
      - db
    environment:
      PMA_HOSTS: db
      PMA_USER: dbuser
      PMA_PASSWORD: user123
